### ISSUE TITLE
CMake simplification

### ISSUE THREAD

**Issue by adriendelsalle** [fastscape-lem/fastscapelib#48]
Hi, thank you for this project @benbovy !

Is `fastscapelib` meant to be used outside a conda env ?
If this is not an expected use case, the CMake files could be simplified to only use `find_package` after installing dependencies through conda/mamba instead of also handling installation from sources.

Let me know!

**Comment by benbovy** [comment]
Thanks @adriendelsalle for looking into this!

I agree that we should simply use `find_package` if we don't need to build/install the dependencies or external tools from source. This could be useful in some cases, though. For example, testing fastscapelib against `xtensor` development version (in CI) is good for anticipating compatibility issues, as `xtensor` is still evolving quite fast. Is there any `gtest` or `benchmark` build option or flag that could be useful to tweak here?

**Comment by adriendelsalle** [comment]
Thanks for the quick reply!
Ok I keep that use case of testing `fastscapelib` against `xtensor` master in mind.

I will open a PR to start a discussion about possible evolutions of the CMake configuration.
