### ISSUE TITLE
Non uniform grids?

### ISSUE THREAD

**Issue by adriendelsalle** [fastscape-lem/fastscapelib#56]
From #51 review by @benbovy 

> I think that it will eventually be useful to support non-uniform profile grids (this could be done later). What's the best approach here?
add another grid class?
is there a way to allow spacing_type be either double or xt_container_t<xt_selector, double, xt_ndims::value>, and statically compute is_uniform depending on the given spacing_type? Could we do this without exposing another template parameter to profile_grid_xt (i.e., infer spacing_type from the type given in the constructor)?

**Comment by adriendelsalle** [comment]
As a first guess, I would say that a dedicated class will offer better performance because the caches of distances will be optimized for the uniform cases.

**Comment by benbovy** [comment]
Agreed for having separate classes, if needed. Closing as this is not needed for now.
