### ISSUE TITLE
Structured grids and looped boundary conditions

### ISSUE THREAD

**Issue by benbovy** [fastscape-lem/fastscapelib#58]
From https://github.com/fastscape-lem/fastscapelib/pull/51#discussion_r552446908

**Comment by benbovy** [comment]
We should maybe drop the case of full periodic boundaries for the four borders of a raster grid after #53.

**Comment by adriendelsalle** [comment]
Hi @benbovy 

From the current implementation, we should drop:
- `profile_grid` horizontal loop
- `raster_grid` horizontal+vertical looped boundaries = make them exclusive

Can you confirm ? They don't correspond to any physical representation?

Thanks!

**Comment by benbovy** [comment]
Yes we can drop those cases!

**Comment by adriendelsalle** [comment]
At this time, I'm not sure we want to remove cases that may be not useful (because not matching any *physical* representation) but still, working.

**Comment by benbovy** [comment]
Yeah, I agree, let's keep them for now.

My only concern is that it might confuse users who don't really know what they are doing, but let's see... (I'd keep this issue open).

**Comment by benbovy** [comment]
It actually makes sense physically (using inner base level nodes as boundary conditions for flow-based processes). Closing.
