### ISSUE TITLE
Reuse cache when changing `raster_connect`

### ISSUE THREAD

**Issue by adriendelsalle** [fastscape-lem/fastscapelib#66]
> In the current implementation, does `queen_grid.create_similar_raster<raster_connect::rook>();` reuse the cache from from `queen_grid`? If not, my concern is that it may waste too much memory for larger grids.

_Originally posted by @benbovy in https://github.com/fastscape-lem/fastscapelib/issues/62#issuecomment-758544475_

**Comment by benbovy** [comment]
Agreed!
