### ISSUE TITLE
Get rid of grid_inner_types?

### ISSUE THREAD

**Issue by benbovy** [fastscape-lem/fastscapelib#67]
I'm wondering if it still makes sense to have a `grid_inner_types` class? When I look at, e.g., #62, aliases are created in grid classes for most (if not all?) types defined in `grid_inner_types`... Is there any good reason to keep it?

**Comment by JohanMabille** [comment]
That's a technical need: you cannot access the inner types of a derived class from the base class in the CRTP pattern. Therefore, you need to define thoses types in an axternal structures, and alias them in the derived class for consistency. This way, bothe the derived and the base class can access them.

**Comment by benbovy** [comment]
Ah I see, that seems to be a good reason to keep it :). Thanks for the explanation @JohanMabille.
