### ISSUE TITLE
Checking field (xtensor container) shape vs. grid shape?

### ISSUE THREAD

**Issue by benbovy** [fastscape-lem/fastscapelib#73]
In many places like `fill_sinks_flat(grid, elevation)` and `flow_graph(elevation)` we need to provide a xtensor container that represents a quantity defined on the nodes of a grid. Obviously, the shape of the container must match the shape of the grid.

How best could we implement checks at runtime for this? Any idea @adriendelsalle @JohanMabille?

**Comment by JohanMabille** [comment]
`xtensor` provides the [same_shape](https://github.com/xtensor-stack/xtensor/blob/master/include/xtensor/xshape.hpp#L40) method that you could use in an assertion if you don't want to perform that check in Release mode.

**Comment by benbovy** [comment]
Ah thanks, good to know! (time for me to dig a bit more into xtensor's documentation).

**Comment by JohanMabille** [comment]
I'm not sure we've documented this one to be honest ;)

**Comment by benbovy** [comment]
It would be nice to have some flexibility in C++ while always enabling the checks in the Python bindings.

Looking at `xtensor/xexception.hpp`, I guess we could do something similar here, e.g., with macros like `FASTSCAPELIB_CHECK_SHAPE`, `FASTSCAPELIB_ENABLE_ASSERT` and/or `FASTSCAPELIB_DISABLE_EXCEPTIONS`?
